<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Oasis_Pipelines\Oasis_Pipelines.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    </ItemGroup>
    
    <ItemGroup>
      <Page Update="DiagramSession.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="PipelineDiagram.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>
    
    <ItemGroup>
      <Reference Include="Oasis_Visual_Pipelines.Operations">
        <HintPath>..\Oasis_Visual_Pipelines.Operations\bin\Debug\net9.0-windows\Oasis_Visual_Pipelines.Operations.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
