<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Page Update="MultiSelectControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="NumericUpDownControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" />
      <PackageReference Include="MaterialDesignThemes" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="MaterialDesignThemes.Wpf">
        <HintPath>..\..\..\..\.nuget\packages\materialdesignthemes\5.3.2\lib\net10.0-windows7.0\MaterialDesignThemes.Wpf.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Oasis_Pipelines.Shared\Oasis_Pipelines.Shared.csproj" />
      <ProjectReference Include="..\Oasis_Pipelines\Oasis_Pipelines.csproj" />
    </ItemGroup>

</Project>
