<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Oasis_Pipelines.Operations.Wpf</RootNamespace>
        <AssemblyName>Oasis_Pipelines.Operations.Wpf</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Oasis_Pipelines.Controls.Wpf\Oasis_Pipelines.Controls.Wpf.csproj" />
        <ProjectReference Include="..\Oasis_Pipelines.Dialogs.Wpf\Oasis_Pipelines.Dialogs.Wpf.csproj" />
        <ProjectReference Include="..\Oasis_Pipelines.Shared.Wpf\Oasis_Pipelines.Shared.Wpf.csproj" />
        <ProjectReference Include="..\Oasis_Pipelines\Oasis_Pipelines.csproj"/>
        <ProjectReference Include="..\Oasis_Pipelines.Operations\Oasis_Pipelines.Operations.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MaterialDesignThemes"/>
    </ItemGroup>
</Project>
